### ISSUE TITLE
Only works on same network

### ISSUE THREAD

**Issue by Pwnmanship** [alexan1/SignalRTC#1]
What works:
1. One client phone that is on the network
2. One client pc which is on the same network
3. You can call and you see eachother.

Now if we take the phone out of the network and use 4g or whatever it doesn't seem to work.

**Comment by alexan1** [comment]
I had the same problem, it worked only on local network. But then I add Google STUN server, this fixed problem.

 ```
var servers = { 'iceServers': [{ 'urls': 'stun:74.125.142.127:19302' }] };
  //var  _iceServers = [{ url: 'stun:74.125.142.127:19302' }], // stun.l.google.com - Firefox does not support DNS names.
```

**Comment by Pwnmanship** [comment]
Still doesn't seem to work. Also doesn't work on your website https://signalrtc.com
Could you try adding a TURN server in your code. You can create one on numb.viagenie.ca for free.

It didn't seem to help in my solution but maybe it does in yours.

**Comment by alexan1** [comment]
Are you sure site doesn't work? I didn't check long time, will check first.

**Comment by alexan1** [comment]
Yes, vidéocommunication doesn't work, will look at this on weekend. Or you can try yourself.

**Comment by alexan1** [comment]
just updated STUN server to: stun:stun.l.google.com:19302

It looks it fixed problem

**Comment by alexan1** [comment]
updating STUN fixed the issue
