### ISSUE TITLE
Self-Hosting

### ISSUE THREAD

**Issue by SaeedVarasteh** [alexan1/SignalRTC#3]
Hello, How can I host this on my own server?

**Comment by alexan1** [comment]
the same as you host your web applications

**Comment by SaeedVarasteh** [comment]
Thank you for your quick response, I meant that you are not provide the client-side web application?

**Comment by alexan1** [comment]
it's in the other repo: https://github.com/alexan1/signalrtc.com

**Comment by SaeedVarasteh** [comment]
Great! Thank you.
